export const dataNation = [
    { label: 'Kinh', id: '1' },
    { label: 'Chứt', id: '2' },
    { label: 'Mường', id: '3' },
    { label: 'Thổ', id: '4' },
    { label: 'Bố Y', id: '5' },
    { label: 'Giáy', id: '6' },
    { label: 'Lào', id: '7' },
    { label: 'Lự', id: '8' },
    { label: 'Nùng', id: '9' },
    { label: 'Sán Chay', id: '10' },
    { label: 'Tày', id: '11' },
    { label: 'Thái', id: '12' },
    { label: 'Cờ Lao', id: '13' },
    { label: 'La Chí', id: '14' },
    { label: 'La Ha', id: '15' },
    { label: 'Pu Péo', id: '16' },
    { label: 'Ba Na', id: '17' },
    { label: 'Brâu', id: '18' },
    { label: 'Bru - Vân Kiều', id: '19' },
    { label: 'Chơ Ro', id: '20' },
    { label: 'Co', id: '21' },
    { label: 'Cơ Ho', id: '22' },
    { label: 'Cơ Tu', id: '23' },
    { label: 'Giẻ Triêng', id: '24' },
    { label: "H'rê", id: '25' },
    { label: 'Kháng', id: '26' },
    { label: 'Khmer', id: '27' },
    { label: 'Khơ Mú', id: '28' },
    { label: 'Mạ', id: '29' },
    { label: 'Mảng', id: '30' },
    { label: 'M’Nông', id: '31' },
    { label: 'Ơ Đu', id: '32' },
    { label: 'Rơ Măm', id: '33' },
    { label: 'Tà Ôi', id: '34' },
    { label: 'Xinh Mun', id: '35' },
    { label: 'Xơ Đăng', id: '36' },
    { label: 'Xtiêng', id: '37' },
    { label: 'Dao', id: '38' },
    { label: 'H’Mông', id: '39' },
    { label: 'Pà Thẻn', id: '40' },
    { label: 'Chăm', id: '41' },
    { label: 'Chu Ru', id: '42' },
    { label: 'Ê Đê', id: '43' },
    { label: 'Gia Rai', id: '44' },
    { label: 'Ra Glai', id: '45' },
    { label: 'Hoa', id: '46' },
    { label: 'Ngái', id: '47' },
    { label: 'Sán Dìu', id: '48' },
    { label: 'Cống', id: '49' },
    { label: 'Hà Nhì', id: '50' },
    { label: 'La Hủ', id: '51' },
    { label: 'Lô Lô', id: '52' },
    { label: 'Phù Lá', id: '53' },
    { label: 'Si La', id: '54' },
];

export const dataReligion = [
    { label: 'Không', id: '1' },
    { label: 'Phật giáo', id: '2' },
    { label: 'Kitô giáo', id: '3' },
    { label: 'Công giáo', id: '4' },
    { label: 'Tin Lành', id: '5' },
    { label: 'Hòa Hảo', id: '6' },
    { label: 'Cao Đài', id: '7' },
    { label: 'Khác', id: '8' },
];

export const dataCivilClass = [
    {
        id: '1',
        label: 'Chuyên viên cao cấp',
        code: '1.001',
        detail: 'Chuyên ngành hành chính (trong cơ quan, tổ chức hành chính)',
    },
    {
        id: '2',
        label: 'Thanh tra viên cao cấp',
        code: '4.023',
        detail: 'Thanh tra',
    },
    {
        id: '3',
        label: 'Kế toán viên cao cấp',
        code: '6.029',
        detail: 'Kế toán tại cơ quan, tổ chức có sử dụng kinh phí NSNN (Công chức A3.2)',
    },
    {
        id: '4',
        label: 'Kiểm tra viên cao cấp thuế',
        code: '6.036',
        detail: 'Thuế',
    },
    {
        id: '5',
        label: 'Kiểm tra viên cao cấp hải quan',
        code: '8.049',
        detail: 'Hải Quan',
    },
    {
        id: '6',
        label: 'Kiểm soát viên cao cấp ngân hàng',
        code: '7.044',
        detail: 'Ngân hàng',
    },
    {
        id: '7',
        label: 'Kiểm toán viên cao cấp',
        code: '6.041',
        detail: 'Kiểm toán NN',
    },
    {
        id: '8',
        label: 'Chấp hành viên cao cấp',
        code: '3.299',
        detail: 'Thi hành án dân sự',
    },
    {
        id: '9',
        label: 'Thẩm tra viên cao cấp',
        code: '3.230',
        detail: 'Thi hành án dân sự',
    },
    {
        id: '10',
        label: 'Kiểm soát viên cao cấp thị trường',
        code: '21.187',
        detail: 'Quản lý thị trường',
    },
    {
        id: '11',
        label: 'Chuyên viên chính',
        code: '1.002',
        detail: 'Chuyên ngành hành chính (trong cơ quan, tổ chức hành chính)',
    },
    {
        id: '12',
        label: 'Thanh tra viên chính',
        code: '4.024',
        detail: 'Thanh tra',
    },
    {
        id: '13',
        label: 'Kế toán viên chính',
        code: '6.030',
        detail: 'Kế toán tại cơ quan, tổ chức có sử dụng kinh phí NSNN (Công chức A2.2)',
    },
    {
        id: '14',
        label: 'Kiểm tra viên chính thuế',
        code: '6.037',
        detail: 'Thuế',
    },
    {
        id: '15',
        label: 'Kiểm tra viên chính hải quan',
        code: '8.050',
        detail: 'Hải Quan',
    },
    {
        id: '16',
        label: 'Kỹ thuật viên bảo quản chính',
        code: '19.220',
        detail: 'Dự trữ quốc gia',
    },
    {
        id: '17',
        label: 'Kiểm soát viên chính ngân hàng',
        code: '7.045',
        detail: 'Ngân hàng',
    },
    {
        id: '18',
        label: 'Kiểm toán viên chính',
        code: '6.042',
        detail: 'Kiểm toán NN',
    },
    {
        id: '19',
        label: 'Chấp hành viên trung cấp',
        code: '3.300',
        detail: 'Thi hành án dân sự',
    },
    {
        id: '20',
        label: 'Thẩm tra viên chính',
        code: '3.231',
        detail: 'Thi hành án dân sự',
    },
    {
        id: '21',
        label: 'Kiểm soát viên chính thị trường',
        code: '21.188',
        detail: 'Quản lý thị trường',
    },
    {
        id: '22',
        label: 'Kiểm dịch viên chính động vật',
        code: '9.315',
        detail: 'Nông nghiệp (Công chức A2.2)',
    },
    {
        id: '23',
        label: 'Kiểm dịch viên chính thực vật',
        code: '9.318',
        detail: 'Nông nghiệp (Công chức A2.2)',
    },
    {
        id: '24',
        label: 'Kiểm soát viên chính đê điều',
        code: '11.081',
        detail: 'Nông nghiệp (Công chức A2.2)',
    },
    {
        id: '25',
        label: 'Kiểm lâm viên chính',
        code: '10.225',
        detail: 'Nông nghiệp',
    },
    {
        id: '26',
        label: 'Kiểm ngư viên chính',
        code: '25.309',
        detail: 'Nông nghiệp',
    },
    {
        id: '27',
        label: 'Thuyền viên kiểm ngư chính',
        code: '25.312',
        detail: 'Nông nghiệp',
    },
    { id: '28', label: 'Văn thư viên chính', code: '2.006', detail: 'Văn thư' },
    {
        id: '29',
        label: 'Chuyên viên',
        code: '1.003',
        detail: 'Chuyên ngành hành chính (trong cơ quan, tổ chức hành chính)',
    },
    {
        id: '30',
        label: 'Thanh tra viên',
        code: '4.025',
        detail: 'Chuyên ngành thanh tra',
    },
    {
        id: '31',
        label: 'Kế toán viên',
        code: '6.031',
        detail: 'Kế toán tại cơ quan, tổ chức có sử dụng kinh phí NSNN',
    },
    { id: '32', label: 'Kiểm tra viên thuế', code: '6.038', detail: 'Thuế' },
    {
        id: '33',
        label: 'Kiểm tra viên hải quan',
        code: '8.051',
        detail: 'Hải Quan',
    },
    {
        id: '34',
        label: 'Kỹ thuật viên bảo quản',
        code: '19.221',
        detail: 'Dự trữ quốc gia',
    },
    {
        id: '35',
        label: 'Kiểm soát viên ngân hàng',
        code: '7.046',
        detail: 'Ngân hàng',
    },
    {
        id: '36',
        label: 'Kiểm toán viên',
        code: '6.043',
        detail: 'Kiểm toán NN',
    },
    {
        id: '37',
        label: 'Chấp hành viên sơ cấp',
        code: '3.301',
        detail: 'Thi hành án dân sự',
    },
    {
        id: '38',
        label: 'Thẩm tra viên',
        code: '3.232',
        detail: 'Thi hành án dân sự',
    },
    {
        id: '39',
        label: 'Thư ký thi hành án',
        code: '3.302',
        detail: 'Thi hành án dân sự',
    },
    {
        id: '40',
        label: 'Kiểm soát viên thị trường',
        code: '21.189',
        detail: 'Quản lý thị trường',
    },
    {
        id: '41',
        label: 'Kiểm dịch viên động vật',
        code: '9.316',
        detail: 'Nông nghiệp',
    },
    {
        id: '42',
        label: 'Kiểm dịch viên thực vật',
        code: '9.319',
        detail: 'Nông nghiệp',
    },
    {
        id: '43',
        label: 'Kiểm soát viên đê điều',
        code: '11.082',
        detail: 'Nông nghiệp',
    },
    { id: '44', label: 'Kiểm lâm viên', code: '10.226', detail: 'Nông nghiệp' },
    { id: '45', label: 'Kiểm ngư viên', code: '25.310', detail: 'Nông nghiệp' },
    {
        id: '46',
        label: 'Thuyền viên kiểm ngư',
        code: '25.313',
        detail: 'Nông nghiệp',
    },
    { id: '47', label: 'Văn thư viện', code: '2.007', detail: 'Văn thư' },
    {
        id: '48',
        label: 'Cán sự',
        code: '1.004',
        detail: 'Chuyên ngành hành chính (trong cơ quan, tổ chức hành chính)',
    },
    {
        id: '49',
        label: 'Kế toán viên trung cấp',
        code: '6.032',
        detail: 'Kế toán tại cơ quan, tổ chức có sử dụng kinh phí NSNN',
    },
    {
        id: '50',
        label: 'Kiểm tra viên trung cấp thuế',
        code: '6.039',
        detail: 'Thuế',
    },
    {
        id: '51',
        label: 'Kiểm tra viên trung cấp hải quan',
        code: '8.052',
        detail: 'Hải Quan',
    },
    {
        id: '52',
        label: 'Kiểm soát viên trung cấp thị trường',
        code: '21.190',
        detail: 'Quản lý thị trường',
    },
    {
        id: '53',
        label: 'Kỹ thuật viên bảo quản trung cấp',
        code: '19.222',
        detail: 'Dự trữ quốc gia',
    },
    {
        id: '54',
        label: 'Thủ kho bảo quản',
        code: '19.223',
        detail: 'Dự trữ quốc gia',
    },
    {
        id: '55',
        label: 'Thủ kho, thủ quỹ ngân hàng',
        code: '7.048',
        detail: 'Ngân hàng',
    },
    {
        id: '56',
        label: 'Nhân viên',
        code: '1.005',
        detail: 'làm việc trong cơ quan, tổ chức hành chính',
    },
    { id: '57', label: 'Nhân viên thuế', code: '6.040', detail: 'Thuế' },
    {
        id: '58',
        label: 'Nhân viên hải quan',
        code: '8.053',
        detail: 'Hải Quan',
    },
    {
        id: '59',
        label: 'Nhân viên Tiền tệ – Kho quỹ',
        code: '7.047',
        detail: 'Ngân hàng',
    },
    {
        id: '60',
        label: 'Thư ký trung cấp thi hành án',
        code: '3.303',
        detail: 'Thi hành án dân sự',
    },
    {
        id: '61',
        label: 'Kỹ thuật viên kiểm dịch động vật',
        code: '9.317',
        detail: 'Nông nghiệp',
    },
    {
        id: '62',
        label: 'Kỹ thuật viên kiểm dịch thực vật',
        code: '9.320',
        detail: 'Nông nghiệp',
    },
    {
        id: '63',
        label: 'Kiểm soát viên trung cấp đê điều',
        code: '11.083',
        detail: 'Nông nghiệp',
    },
    {
        id: '64',
        label: 'Kiểm lâm viên trung cấp',
        code: '10.228',
        detail: 'Nông nghiệp',
    },
    {
        id: '65',
        label: 'Kiểm ngư viên trung cấp',
        code: '25.311',
        detail: 'Nông nghiệp',
    },
    {
        id: '66',
        label: 'Thuyền viên kiểm ngư trung cấp',
        code: '25.314',
        detail: 'Nông nghiệp',
    },
    {
        id: '67',
        label: 'Văn thư viên trung cấp',
        code: '2.008',
        detail: 'Văn thư',
    },
    {
        id: '68',
        label: 'Thủ quỹ cơ quan, đơn vị',
        code: '6.035',
        detail: 'Văn thư',
    },
    {
        id: '69',
        label: 'Nhân viên bảo vệ kho dự trữ',
        code: '19.224',
        detail: 'Dự trữ quốc gia',
    },
];

export const dataEducationLevel = [
    {id: 1, label: "Sơ cấp"},
    {id: 2, label: "Trung cấp"},
    {id: 3, label: "Cao đẳng"},
    {id: 4, label: "Đại học"},
    {id: 5, label: "Thạc sĩ"},
    {id: 6, label: "Tiến sĩ"},    
];

export const dataPoliticalTheory = [
    {id: 1, label: "Sơ cấp"},
    {id: 2, label: "Trung cấp"},
    {id: 3, label: "Cao cấp"},
    {id: 4, label: "Cử nhân"},
];

export const dataBloodGroup = [
    {id: 1, label: "Nhóm A"},
    {id: 1, label: "Nhóm B"},
    {id: 1, label: "Nhóm AB"},
    {id: 1, label: "Nhóm O"},
];
