export const ONCHANGE_SUCCESS = 'ONCHANGE_SUCCESS';
export const ONCHANGE_FAIL = 'ONCHANGE_FAIL';

export const FETCH_ADDRESS_LOADING = 'FETCH_ADDRESS_LOADING';
export const FETCH_ADDRESS_SUCCESS = 'FETCH_ADDRESS_SUCCESS';
export const FETCH_ADDRESS_FAIL = 'FETCH_ADDRESS_FAIL';